#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # Portfolio Jekyll Theme

  Este é um site onde posso colocar alguns tutorias e projetos.
contact: >
  # Contact

  Contact me [through my email](mailto:andrezio@live.com) or [tweet at me](https://twitter.com/andrezio). 
#You may contact me [through my email](mailto:l.nguyen.paul@gmail.com) or [tweet at me](https://twitter.com/intent/tweet?text=%40paululele) if you have any questions or would like to bring up any issues.

#-------------------------------
# Work Section

projects:
- {name: 'Project One', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Project Two', folder: 'proj-2', file: 'projects/proj-2.html'}
#- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}
#- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
#- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/andrezio'}
- {icon: 'instagram', link: 'https://www.instagram.com/andreziojudas/?hl=pt-br'}
- {icon: 'github', link: 'https://github.com/abndre'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/andrezio/'}
- {icon: 'envelope', link: 'mailto:andrezio@live.com'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UCW9ml6ydUdNX0omtJ5sqctw'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
